### ISSUE TITLE
DNS_PROBE_FINISHED_NO_INTERNET

### ISSUE THREAD

**Issue by atxiii** [geph-official/geph4#25] opened 2021-07-04 23:56 UTC
Hi there,
I'm using geph4.4 in mx linux, after disconnect, I see this error in browseres: "DNS_PROBE_FINISHED_NO_INTERNET".  therefore, I have to restart network and restart machin for resolving this issue. Is there any way to fix the network configuration without restarting machin or network?

Thanks in advance.

**Comment by nullchinchilla** [comment] 2021-07-06 19:27
Are you using proxy mode or VPN mode?

**Comment by charleschege** [comment] 2021-07-06 19:41
This is the same issue I have experience with geph in VPN mode. It does not reset the network settings to the previous ones or the default ones like other vpn software do.

The solution is to restart the machine which is really annoying. There needs to be a solution to reset the network? How do other VPNs do it?

**Comment by nullchinchilla** [comment] 2021-07-06 19:42
This is very strange because on my computer it works properly. What distros are you guys using?

**Comment by charleschege** [comment] 2021-07-06 19:48
I am using KDE Neon which is Ubuntu 20.04 pre-loaded with KDE Plasma Desktop

**Comment by charleschege** [comment] 2021-07-06 20:07
> This is very strange because on my computer it works properly, and settings are correctly removed after disconnecting. What distros are you guys using?

I have thought about this and decided to take a deeper look at it.

I have a two laptops, I have been using one of them for years and it is the one I had an issue with but the new one with a fresh install does not seem to have an issue.
Could it be possible that some updates to the system solved the issue?

But I will have to check my older system

**Comment by charleschege** [comment] 2021-07-06 20:40
I can confirm that resolving the DNS is the problem. In VPN mode, Geph is unable to reset the default DNS settings or trigger something in the system to show it is not longer in use.

I think this might be caused by the fact that in VPN mode, DNS resolution is still protected to prevent an IP leak.

Geph need to have a solution to remove blocking the IP feature. For example, protonvpn has this feature and it's called a kill switch. There is the ability to disable this kill switch and restore normal dns settings which works really well.

I think Geph needs such a feature because currently all the dns requests try to be routed through geph even though geph is disabled and not connected to a geph node.

But if I don't logout and connect geph to a geph node, everything works fine. However if I logout and try logging in again, even Geph app is no longer able to establish a connection

**Comment by atxiii** [comment] 2021-07-07 19:51
> Are you using proxy mode or VPN mode?

I'm using VPN mode

**Comment by atxiii** [comment] 2021-07-07 20:51
> This is the same issue I have experience with geph in VPN mode. It does not reset the network settings to the previous ones or the default ones like other vpn software do.
> 
> The solution is to restart the machine which is really annoying. There needs to be a solution to reset the network? How do other VPNs do it?

I resolved this issue with way:

1.  When you disconnected the VPN, then go to "Settings" and disable  "Always use bridges" feature. 
2. Back to  "Overview" tab and hit on connect then disconnect.
3. Close App

**Comment by atxiii** [comment] 2021-07-12 06:59
This issue fixed on version 4.4.5.
Thank you so much!

**Closed** 2021-07-12 06:59 UTC
